### PR TITLE
Fix npm package

### PR DESCRIPTION
**Pull request by dnoliver**
Add missing dependency in package.json
Merge changes from @arfoll fork
Add Travis jobs with simple load test for node 4, 5, and 6

### CODE REVIEW

**Review by dnoliver — COMMENTED** [review]
@arfoll @Propanu I made the integration test using the upm xml.tar.gz posted on https://iotdk.intel.com/docs/upm/v1.3.0/xml.tar.gz.

The travis job is passing, but that is because the command always exit with code 0. docgen is having problems to parse those file. Here is the [travis log](https://travis-ci.org/intel-iot-devkit/doxygen2jsdoc/jobs/257045815#L389)

The stacktrace is:

```
Unhandled rejection Error: NYI Unknown Object Type: orderedlist
    at /home/travis/build/intel-iot-devkit/doxygen2jsdoc/xml2js.js:893:17
    at arrayReduce (/home/travis/build/intel-iot-devkit/doxygen2jsdoc/node_modules/lodash/index.js:1497:23)
    at Function.<anonymous> (/home/travis/build/intel-iot-devkit/doxygen2jsdoc/node_modules/lodash/index.js:3377:13)
    at getText (/home/travis/build/intel-iot-devkit/doxygen2jsdoc/xml2js.js:859:12)
    at /home/travis/build/intel-iot-devkit/doxygen2jsdoc/xml2js.js:865:26
```

**Comment by dnoliver** [comment]
I just noticed that this entire repo is copied and pasted in upm https://github.com/intel-iot-devkit/upm/tree/master/doxy

there are some changes done there. I will try to bring them back here

**Comment by Propanu** [comment]
For the most part we modified the base yuidoc templates, but since they live in their own folder I see no reason why this can't become a submodule for UPM too.

**Comment by dnoliver** [comment]
This is the coverage summary for the e2e tests:

```
----------------------------------|----------|----------|----------|----------|----------------|
File                              |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------------------------------|----------|----------|----------|----------|----------------|
 doxygen2jsdoc\                   |    77.42 |    71.69 |    74.07 |    77.75 |                |
  docgen.js                       |       75 |      100 |    57.14 |    73.68 | 52,53,57,58,75 |
  tolower.js                      |    93.62 |       75 |      100 |    93.62 |    101,102,127 |
  xml2js.js                       |    75.63 |    71.52 |    73.11 |    76.03 |... 747,819,897 |
 doxygen2jsdoc\generators\jsdoc\  |    91.67 |       75 |    81.82 |    91.67 |                |
  generator.js                    |    91.67 |       75 |    81.82 |    91.67 |          33,85 |
 doxygen2jsdoc\generators\ternjs\ |    94.64 |       60 |    88.89 |    94.64 |                |
  generator.js                    |    94.64 |       60 |    88.89 |    94.64 |       33,42,46 |
 doxygen2jsdoc\generators\yuidoc\ |    93.18 |    66.67 |       90 |    93.18 |                |
  generator.js                    |    93.18 |    66.67 |       90 |    93.18 |      38,44,140 |
----------------------------------|----------|----------|----------|----------|----------------|
All files                         |    80.81 |    70.83 |    77.72 |    81.14 |                |
----------------------------------|----------|----------|----------|----------|----------------|

```

I hope it could be enough for now. I will have to change mraa and upm repos. If I found more problems there, I will upload more e2e tests

Eslint is also failing now. It throws this errors and warnings :
```
/home/travis/build/intel-iot-devkit/doxygen2jsdoc/docgen.js
  69:14  warning  Avoid nesting promises  promise/no-nesting
/home/travis/build/intel-iot-devkit/doxygen2jsdoc/xml2js.js
  159:11  error    Each then() should return a value or throw  promise/always-return
  180:18  warning  Avoid nesting promises                      promise/no-nesting
  182:13  error    Each then() should return a value or throw  promise/always-return
  202:7   error    Each then() should return a value or throw  promise/always-return
  226:7   error    Each then() should return a value or throw  promise/always-return
  227:16  warning  Avoid nesting promises                      promise/no-nesting
  228:11  error    Each then() should return a value or throw  promise/always-return
  261:14  warning  Avoid nesting promises                      promise/no-nesting
  261:14  warning  Avoid nesting promises                      promise/no-nesting
  275:20  warning  Avoid nesting promises                      promise/no-nesting
  275:74  error    Each then() should return a value or throw  promise/always-return
  301:14  warning  Avoid nesting promises                      promise/no-nesting
  301:58  error    Each then() should return a value or throw  promise/always-return
  306:84  error    Unnecessary escape character: \*            no-useless-escape
```

but this requires a big refactorization on how xml2js works.

**Comment by dnoliver** [comment]
I was taking a look at the mraa docgen, and I saw that a bunch of things are excluded from the documentation. From the log, I can see that `void *`, `std::string *`, or actually any pointer is taken as a invalid type. What that means is that this command cannot convert that into a valid Javascript type. should we take that into account? 

```
Aio.Aio! is omitted from JS documentation.
  Error: parameter aio_context has invalid type void *
Gpio.Gpio! is omitted from JS documentation.
  Error: parameter gpio_context has invalid type void *
Gpio.isr is omitted from JS documentation.
  Error: parameter args has invalid type void *
I2c.I2c! is omitted from JS documentation.
  Error: parameter i2c_context has invalid type void *
I2c.read is omitted from JS documentation.
  Error: parameter data has invalid type uint8_t *
I2c.readBytesReg is omitted from JS documentation.
  Error: parameter data has invalid type uint8_t *
I2c.write is omitted from JS documentation.
  Error: parameter data has invalid type const uint8_t *
Iio.Iio! is omitted from JS documentation.
  Error: parameter deviceName has invalid type const std::string *
Iio.readInt is omitted from JS documentation.
  Error: parameter attributeName has invalid type const std::string *
Iio.readFloat is omitted from JS documentation.
  Error: parameter attributeName has invalid type const std::string *
Iio.writeInt is omitted from JS documentation.
  Error: parameter attributeName has invalid type const std::string *
Iio.writeFloat is omitted from JS documentation.
  Error: parameter attributeName has invalid type const std::string *
IioHandler.onIioEvent is omitted from JS documentation.
  Error: parameter eventData has invalid type const IioEventData *
Pwm.Pwm! is omitted from JS documentation.
  Error: parameter pwm_context has invalid type void *
Spi.Spi!! is omitted from JS documentation.
  Error: parameter spi_context has invalid type void *
Spi.write is omitted from JS documentation.
  Error: parameter txBuf has invalid type uint8_t *
  Error: returns invalid type uint8_t *
Spi.writeWord! is omitted from JS documentation.
  Error: parameter txBuf has invalid type uint16_t *
  Error: returns invalid type uint16_t *
Spi.transfer is omitted from JS documentation.
  Error: parameter txBuf has invalid type uint8_t *
  Error: parameter rxBuf has invalid type uint8_t *
Spi.transfer_word is omitted from JS documentation.
  Error: parameter txBuf has invalid type uint16_t *
  Error: parameter rxBuf has invalid type uint16_t *
Uart.Uart!! is omitted from JS documentation.
  Error: parameter uart_context has invalid type void *
UartOW.reset is omitted from JS documentation.
  Error: returns invalid type mraa::Result
UartOW.search is omitted from JS documentation.
  Error: parameter id has invalid type uint8_t *
  Error: returns invalid type mraa::Result
UartOW.command is omitted from JS documentation.
  Error: parameter id has invalid type uint8_t *
  Error: returns invalid type mraa::Result
UartOW.command! is omitted from JS documentation.
  Error: returns invalid type mraa::Result
UartOW.crc8 is omitted from JS documentation.
  Error: parameter buffer has invalid type uint8_t *
```

**Comment by dnoliver** [comment]
I will merge this into master

**Pull request merged**
